numero1 = int(input("Dame un numero entero: "))
numero2 = int(input("Dame otro: "))

print("------------------------------------------------------")
print (f"La suma de estos numeros es {numero1 + numero2}")
print("------------------------------------------------------")
print (f"Las restas serían {numero1 - numero2} o al revés {numero2 - numero1}")
print("------------------------------------------------------")
print (f"Divididos serían {numero1 / numero2} y al revés {numero2 / numero1}")
print("------------------------------------------------------")
print (f"La multiplicacion sería {numero1 * numero2}")
print("------------------------------------------------------")
